/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Paneles;

import Data.Infrastructure.Hospital;

/**
 *
 * @author oscar
 */
public class aboutHospital extends javax.swing.JPanel {

	/**
	 * Creates new form aboutHospital
	 */
	public aboutHospital() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelTelephone = new javax.swing.JLabel();
        labelNumOfOffices = new javax.swing.JLabel();
        labelNumOfRooms = new javax.swing.JLabel();

        labelName.setText("jLabel1");

        labelAddress.setText("jLabel2");

        labelTelephone.setText("jLabel3");

        labelNumOfOffices.setText("jLabel4");

        labelNumOfRooms.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNumOfRooms)
                    .addComponent(labelNumOfOffices)
                    .addComponent(labelTelephone)
                    .addComponent(labelAddress)
                    .addComponent(labelName))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelName)
                .addGap(40, 40, 40)
                .addComponent(labelAddress)
                .addGap(45, 45, 45)
                .addComponent(labelTelephone)
                .addGap(38, 38, 38)
                .addComponent(labelNumOfOffices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(labelNumOfRooms)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNumOfOffices;
    private javax.swing.JLabel labelNumOfRooms;
    private javax.swing.JLabel labelTelephone;
    // End of variables declaration//GEN-END:variables

	public void setHospital(Hospital h) {
		if(h != null){
			this.labelName.setText(h.getName());
			this.labelAddress.setText(h.getAddress());
			this.labelTelephone.setText("Tel: " + h.getTelephone());
			this.labelNumOfOffices.setText("Number of doctor offices: " + h.getNumOfDoctorsOffices());
			this.labelNumOfRooms.setText("Number of rooms: " + h.getNumOfRooms());
		}
		else{
			this.labelName.setText("No hospital created yet");
			this.labelAddress.setText("");
			this.labelNumOfOffices.setText("");
			this.labelNumOfRooms.setText("");
			this.labelTelephone.setText("");
		}
	}
}
