/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Paneles;

import Data.Infrastructure.Hospital;
import Exceptions.NotValidNumber;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author alanp
 */
public class CreateNewHospital extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewHospital
     */
    public CreateNewHospital() {
        initComponents();
    }

	public JButton getSaveButton() {
		return saveButton;
	}
	
	public Hospital getHospital(){
		int numOfDoctorsOffice = Integer.parseInt(this.numOfDoctorsOfficeField.getText());
		int numOfRoomsField = Integer.parseInt(this.numOfRoomsField.getText());
		Hospital h = new Hospital(
			this.nameField.getText(),
			this.addresField.getText(),
			this.telephoneField.getText(),
			numOfDoctorsOffice,
			numOfRoomsField
		);
		return h;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        telephoneLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        numOfRoomsLabel = new javax.swing.JLabel();
        numOfDoctorsOfficeLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        telephoneField = new javax.swing.JTextField();
        addresField = new javax.swing.JTextField();
        numOfRoomsField = new javax.swing.JTextField();
        numOfDoctorsOfficeField = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Crear Hospital"));

        nameLabel.setText("Nombre:");

        telephoneLabel.setText("Teléfono:");

        addressLabel.setText("Dirección:");

        numOfRoomsLabel.setText("Número de habitaciones:");

        numOfDoctorsOfficeLabel.setText("Número de consultorios:");

        saveButton.setText("Guardar");
        saveButton.setToolTipText("");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(telephoneLabel)
                            .addComponent(addressLabel)
                            .addComponent(numOfRoomsLabel)
                            .addComponent(numOfDoctorsOfficeLabel))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(telephoneField)
                            .addComponent(addresField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numOfDoctorsOfficeField, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(numOfRoomsField))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneLabel)
                    .addComponent(telephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfRoomsLabel)
                    .addComponent(numOfRoomsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numOfDoctorsOfficeLabel)
                    .addComponent(numOfDoctorsOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 26, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if(this.addresField.getText().isEmpty() == false && this.nameField.getText().isEmpty() == false && this.numOfRoomsField.getText().isEmpty() == false && this.numOfDoctorsOfficeField.getText().isEmpty() == false && this.telephoneField.getText().isEmpty() == false)
        {
            Hospital H = new Hospital();
            H.setAddress(this.addresField.getText());
            H.setName(this.nameField.getText());
        
            try {
                H.setNumOfRooms(Integer.valueOf(this.numOfRoomsField.getText()));
            } catch (NotValidNumber ex) {
                //TODO
            }
        
            try {
                H.setNumOfDoctorsOffices(Integer.valueOf(this.numOfDoctorsOfficeField.getText()));
            } catch (NotValidNumber ex) {
                //TODO
            }
        
            try {
                H.setTelephone(this.telephoneField.getText());
            } catch (NotValidNumber ex) {
                //TODO
            }
        
            this.hospitalAGuardar = new Hospital(H);
        }else {
            JOptionPane.showMessageDialog(null, "Uno de los cuadros se encuentra vacío. Favor de llenar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed


    private Hospital hospitalAGuardar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField numOfDoctorsOfficeField;
    private javax.swing.JLabel numOfDoctorsOfficeLabel;
    private javax.swing.JTextField numOfRoomsField;
    private javax.swing.JLabel numOfRoomsLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField telephoneField;
    private javax.swing.JLabel telephoneLabel;
    // End of variables declaration//GEN-END:variables

	public void clearFields() {
		this.addresField.setText("");
		this.nameField.setText("");
		this.numOfDoctorsOfficeField.setText("");
		this.numOfRoomsField.setText("");
		this.telephoneField.setText("");
	}
        
        public Hospital newHopital(){
            return this.hospitalAGuardar;
        }
}
