/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Paneles;

import Data.Infrastructure.DoctorsOffice;
import Data.Infrastructure.Hospital;
import Data.People.Doctor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author alanp
 */
public class CreateNewDoctorsOffice extends javax.swing.JPanel {

	private Hospital hospital;
    /**
     * Creates new form CreateNewDoctorsOffice
     */
    public CreateNewDoctorsOffice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        flloorLabel = new javax.swing.JLabel();
        monthlyRentLabel = new javax.swing.JLabel();
        idDoctorLabel = new javax.swing.JLabel();
        floorField = new javax.swing.JTextField();
        monthlyRentField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        selectDoctor = new javax.swing.JComboBox<>();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Crear Consultorio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 13))); // NOI18N

        flloorLabel.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        flloorLabel.setText("Piso:");

        monthlyRentLabel.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        monthlyRentLabel.setText("Renta mensual:");

        idDoctorLabel.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        idDoctorLabel.setText("Doctor:");

        floorField.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N

        monthlyRentField.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N

        saveButton.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        saveButton.setText("Guardar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        selectDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(saveButton)
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flloorLabel)
                    .addComponent(monthlyRentLabel)
                    .addComponent(idDoctorLabel))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectDoctor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthlyRentField, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(floorField)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flloorLabel)
                    .addComponent(floorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthlyRentLabel)
                    .addComponent(monthlyRentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idDoctorLabel)
                    .addComponent(selectDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel flloorLabel;
    private javax.swing.JTextField floorField;
    private javax.swing.JLabel idDoctorLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField monthlyRentField;
    private javax.swing.JLabel monthlyRentLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> selectDoctor;
    // End of variables declaration//GEN-END:variables

	public DoctorsOffice getOffice() {
		DoctorsOffice dof = null;
		if(!this.floorField.getText().isEmpty() && !this.monthlyRentField.getText().isEmpty()){
			if(this.getSelectedDoctorId().equals("Ningún")){
				dof = new DoctorsOffice(
                            Integer.parseInt(this.floorField.getText()),
                            Float.parseFloat(this.monthlyRentField.getText())
                    );
			}
			else{
				dof = new DoctorsOffice(
                            Integer.parseInt(this.floorField.getText()),
                            Float.parseFloat(this.monthlyRentField.getText()),
                            this.getSelectedDoctorId()
                    );
			}
		}
		else{
			JOptionPane.showMessageDialog(null, "Por favor, no deje el espacio de Piso y/o el de Renta Mensual en blanco.", "ERROR", JOptionPane.ERROR_MESSAGE);
		}
		return dof;
	}

	public javax.swing.JButton getSaveButton() {
		return this.saveButton;
	}
        
	public void clearFields(){
		this.floorField.setText("");
		this.monthlyRentField.setText("");
	}
	
	public void setHospital(Hospital hospital){	
		this.hospital = hospital;
		int doctorNumber = hospital.getDoctors().size() + 1;
		String[] items = new String[doctorNumber];
		//Hardcoded string, keep it here, used for determining if office has doctor or not
		items[0] = "Ningún";
		for(int i = 1 ; i < doctorNumber ; i++){
			//Do not forget that i has 1 too much for getDoctors, has to be lowered
			Doctor doc = hospital.getDoctors().get(i - 1);
			items[i] = doc.getId() + " " + doc.getFirstName() + " " + doc.getLastName();
		}
		this.selectDoctor.setModel(new DefaultComboBoxModel<>(items));
	}

	private String getSelectedDoctorId(){
		return this.selectDoctor.getSelectedItem().toString().split(" ")[0];
	}
}
