/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Paneles;

import Data.Infrastructure.Hospital;
import Exceptions.NotValidNumber;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author alanp
 */
public class EditHospital extends javax.swing.JPanel {
	
    protected String name;
    protected String telephone;
    protected String address;
    protected int numOfRooms;
    protected int numOfDoctorsOffices;
    /**
     * Creates new form EditHospital
     */
    public EditHospital() {
        initComponents();
    }

	public JButton getSaveButton() {
		return saveButton;
	}
        
        public void save(){
        if(!this.nameField.getText().isEmpty() && !this.addressField.getText().isEmpty() && !this.telephoneField.getText().isEmpty() && !this.numOfDoctorsOfficeField.getText().isEmpty() && !this.numOfRoomsField.getText().isEmpty())
            {
            this.name = nameField.getText();
            this.telephone = telephoneField.getText();
            this.address = addressField.getText();
            this.numOfRooms = Integer.valueOf(this.numOfRoomsField.getText());
            this.numOfDoctorsOffices = Integer.valueOf(this.numOfDoctorsOfficeField.getText());
            
            this.HospitalEdited = new Hospital();
            this.HospitalEdited.setAddress(this.address);
            this.HospitalEdited.setName(this.name);
            try {
                this.HospitalEdited.setTelephone(this.telephone);
            } catch (NotValidNumber ex) {
                //TODO
            }
            try {
                this.HospitalEdited.setNumOfDoctorsOffices(this.numOfDoctorsOffices);
            } catch (NotValidNumber ex) {
                //TODO
            }
            try {
                this.HospitalEdited.setNumOfRooms(this.numOfRooms);
            } catch (NotValidNumber ex) {
                //TODO
            }
            
            JOptionPane.showMessageDialog(null, "Cambios guardados.", "Operacon Exitosa", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Uno de los cuadros se encuentra vacío. Favor de llenar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        telephoneLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        telephoneField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        numOfRoomsLabel = new javax.swing.JLabel();
        numOfDoctorsOfficeLabel = new javax.swing.JLabel();
        numOfDoctorsOfficeField = new javax.swing.JTextField();
        numOfRoomsField = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Editar Hospital"));

        saveButton.setText("Guardar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nameLabel.setText("Nombre:");

        telephoneLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        telephoneLabel.setText("Teléfono:");

        addressLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        addressLabel.setText("Dirección:");

        numOfRoomsLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        numOfRoomsLabel.setText("Número de habitaciones:");

        numOfDoctorsOfficeLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        numOfDoctorsOfficeLabel.setText("Número de consultorios:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(telephoneLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(188, 188, 188)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(telephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 175, Short.MAX_VALUE))
                                    .addComponent(nameField)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numOfDoctorsOfficeLabel)
                                    .addComponent(numOfRoomsLabel)
                                    .addComponent(addressLabel))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressField)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numOfDoctorsOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numOfRoomsField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneLabel))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfRoomsLabel)
                    .addComponent(numOfRoomsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfDoctorsOfficeLabel)
                    .addComponent(numOfDoctorsOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_saveButtonActionPerformed


    private Hospital HospitalEdited;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField numOfDoctorsOfficeField;
    private javax.swing.JLabel numOfDoctorsOfficeLabel;
    private javax.swing.JTextField numOfRoomsField;
    private javax.swing.JLabel numOfRoomsLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField telephoneField;
    private javax.swing.JLabel telephoneLabel;
    // End of variables declaration//GEN-END:variables

	String getHospitalName() {
		return this.nameField.getText();
	}

	String getHospitalAddress() {
		return this.addressField.getText();
	}

	String getHospitalTelephone() {
		return this.telephoneField.getText();
	}
        
        public Hospital getHospital(){
            return this.HospitalEdited;
        }

	public void setFields(Hospital hospital) {
		this.addressField.setText(hospital.getAddress());
		this.telephoneField.setText(hospital.getTelephone());
		this.nameField.setText(hospital.getName());
                this.numOfDoctorsOfficeField.setText(Integer.toString(hospital.getNumOfDoctorsOffices()));
                this.numOfRoomsField.setText(Integer.toString(hospital.getNumOfRooms()));
	}
	
}
