/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Paneles;

import Data.Infrastructure.Hospital;
import java.awt.CardLayout;
import java.util.ArrayList;

/**
 *
 * @author oscar
 */
public class MainWindow extends javax.swing.JFrame {

	/**
	 * Variable keeping all the data from all the hospitals
	 */
	private ArrayList<Hospital> hospitals;
	
	/**
	 * Creates new form MainWindow
	 */
	public MainWindow() {
		this.hospitals = new ArrayList<>();
		initComponents();
		initSaveButtonsListeners();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        inicioPanel = new javax.swing.JPanel();
        inicioPanel1 = new Interfaz.Paneles.InicioPanel();
        newHospital = new javax.swing.JPanel();
        createNewHospital1 = new Interfaz.Paneles.CreateNewHospital();
        newOffice = new javax.swing.JPanel();
        createNewDoctorsOffice1 = new Interfaz.Paneles.CreateNewDoctorsOffice();
        newPatient = new javax.swing.JPanel();
        newDoctor = new javax.swing.JPanel();
        editPatient = new javax.swing.JPanel();
        editOffice = new javax.swing.JPanel();
        editDoctorsOffice1 = new Interfaz.Paneles.EditDoctorsOffice();
        editDoctor = new javax.swing.JPanel();
        removePatient = new javax.swing.JPanel();
        deleteOffice = new javax.swing.JPanel();
        deleteDoctorsOffice1 = new Interfaz.Paneles.DeleteDoctorsOffice();
        removeDoctor = new javax.swing.JPanel();
        aboutHospital = new javax.swing.JPanel();
        selectHospital = new javax.swing.JPanel();
        showDoctor = new javax.swing.JPanel();
        showDoctor1 = new Interfaz.Paneles.ShowDoctor();
        menuBar = new javax.swing.JMenuBar();
        inicioMenu = new javax.swing.JMenu();
        menuHospital = new javax.swing.JMenu();
        menuAboutHospital = new javax.swing.JMenuItem();
        menuNewHospital = new javax.swing.JMenuItem();
        menuSelectHospital = new javax.swing.JMenuItem();
        menuOffice = new javax.swing.JMenu();
        menuNewOffice = new javax.swing.JMenuItem();
        menuEditOffice = new javax.swing.JMenuItem();
        menuRemoveOffice = new javax.swing.JMenuItem();
        menuDoctor = new javax.swing.JMenu();
        menuNewDoctor = new javax.swing.JMenuItem();
        menuEditDoctor = new javax.swing.JMenuItem();
        menuRemoveDoctor = new javax.swing.JMenuItem();
        menuPatient = new javax.swing.JMenu();
        menuNewPatient = new javax.swing.JMenuItem();
        menuEditPatient = new javax.swing.JMenuItem();
        menuRemovePatient = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenu();
        searchDoctor = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout inicioPanelLayout = new javax.swing.GroupLayout(inicioPanel);
        inicioPanel.setLayout(inicioPanelLayout);
        inicioPanelLayout.setHorizontalGroup(
            inicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(inicioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inicioPanelLayout.setVerticalGroup(
            inicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inicioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(inicioPanel, "inicioPanel");

        javax.swing.GroupLayout newHospitalLayout = new javax.swing.GroupLayout(newHospital);
        newHospital.setLayout(newHospitalLayout);
        newHospitalLayout.setHorizontalGroup(
            newHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newHospitalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createNewHospital1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                .addContainerGap())
        );
        newHospitalLayout.setVerticalGroup(
            newHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newHospitalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createNewHospital1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(newHospital, "newHospital");

        javax.swing.GroupLayout newOfficeLayout = new javax.swing.GroupLayout(newOffice);
        newOffice.setLayout(newOfficeLayout);
        newOfficeLayout.setHorizontalGroup(
            newOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newOfficeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createNewDoctorsOffice1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                .addContainerGap())
        );
        newOfficeLayout.setVerticalGroup(
            newOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newOfficeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createNewDoctorsOffice1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(newOffice, "newOffice");

        javax.swing.GroupLayout newPatientLayout = new javax.swing.GroupLayout(newPatient);
        newPatient.setLayout(newPatientLayout);
        newPatientLayout.setHorizontalGroup(
            newPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        newPatientLayout.setVerticalGroup(
            newPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.add(newPatient, "newPatient");

        javax.swing.GroupLayout newDoctorLayout = new javax.swing.GroupLayout(newDoctor);
        newDoctor.setLayout(newDoctorLayout);
        newDoctorLayout.setHorizontalGroup(
            newDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        newDoctorLayout.setVerticalGroup(
            newDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.add(newDoctor, "newDoctor");

        javax.swing.GroupLayout editPatientLayout = new javax.swing.GroupLayout(editPatient);
        editPatient.setLayout(editPatientLayout);
        editPatientLayout.setHorizontalGroup(
            editPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        editPatientLayout.setVerticalGroup(
            editPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.add(editPatient, "editPatient");

        javax.swing.GroupLayout editOfficeLayout = new javax.swing.GroupLayout(editOffice);
        editOffice.setLayout(editOfficeLayout);
        editOfficeLayout.setHorizontalGroup(
            editOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editOfficeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editDoctorsOffice1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                .addContainerGap())
        );
        editOfficeLayout.setVerticalGroup(
            editOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editOfficeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editDoctorsOffice1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(editOffice, "editOffice");

        javax.swing.GroupLayout editDoctorLayout = new javax.swing.GroupLayout(editDoctor);
        editDoctor.setLayout(editDoctorLayout);
        editDoctorLayout.setHorizontalGroup(
            editDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        editDoctorLayout.setVerticalGroup(
            editDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.add(editDoctor, "editDoctor");

        javax.swing.GroupLayout removePatientLayout = new javax.swing.GroupLayout(removePatient);
        removePatient.setLayout(removePatientLayout);
        removePatientLayout.setHorizontalGroup(
            removePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        removePatientLayout.setVerticalGroup(
            removePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.add(removePatient, "removePatient");

        javax.swing.GroupLayout deleteOfficeLayout = new javax.swing.GroupLayout(deleteOffice);
        deleteOffice.setLayout(deleteOfficeLayout);
        deleteOfficeLayout.setHorizontalGroup(
            deleteOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteOfficeLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(deleteDoctorsOffice1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        deleteOfficeLayout.setVerticalGroup(
            deleteOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteOfficeLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(deleteDoctorsOffice1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(deleteOffice, "removeOffice");

        javax.swing.GroupLayout removeDoctorLayout = new javax.swing.GroupLayout(removeDoctor);
        removeDoctor.setLayout(removeDoctorLayout);
        removeDoctorLayout.setHorizontalGroup(
            removeDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        removeDoctorLayout.setVerticalGroup(
            removeDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.add(removeDoctor, "removeDoctor");

        javax.swing.GroupLayout aboutHospitalLayout = new javax.swing.GroupLayout(aboutHospital);
        aboutHospital.setLayout(aboutHospitalLayout);
        aboutHospitalLayout.setHorizontalGroup(
            aboutHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        aboutHospitalLayout.setVerticalGroup(
            aboutHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.add(aboutHospital, "aboutHospital");

        javax.swing.GroupLayout selectHospitalLayout = new javax.swing.GroupLayout(selectHospital);
        selectHospital.setLayout(selectHospitalLayout);
        selectHospitalLayout.setHorizontalGroup(
            selectHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        selectHospitalLayout.setVerticalGroup(
            selectHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.add(selectHospital, "selectHospital");

        javax.swing.GroupLayout showDoctorLayout = new javax.swing.GroupLayout(showDoctor);
        showDoctor.setLayout(showDoctorLayout);
        showDoctorLayout.setHorizontalGroup(
            showDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showDoctor1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        showDoctorLayout.setVerticalGroup(
            showDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDoctorLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(showDoctor1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(showDoctor, "showDoctor");

        inicioMenu.setText("Inicio");
        inicioMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMenuMouseClicked(evt);
            }
        });
        inicioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioMenuActionPerformed(evt);
            }
        });
        menuBar.add(inicioMenu);

        menuHospital.setText("Hospital");

        menuAboutHospital.setText("About");
        menuAboutHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutHospitalActionPerformed(evt);
            }
        });
        menuHospital.add(menuAboutHospital);

        menuNewHospital.setText("New");
        menuNewHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewHospitalActionPerformed(evt);
            }
        });
        menuHospital.add(menuNewHospital);

        menuSelectHospital.setText("Select");
        menuSelectHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSelectHospitalActionPerformed(evt);
            }
        });
        menuHospital.add(menuSelectHospital);

        menuBar.add(menuHospital);

        menuOffice.setText("Consultorio");

        menuNewOffice.setText("Add");
        menuNewOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewOfficeActionPerformed(evt);
            }
        });
        menuOffice.add(menuNewOffice);

        menuEditOffice.setText("Edit");
        menuEditOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditOfficeActionPerformed(evt);
            }
        });
        menuOffice.add(menuEditOffice);

        menuRemoveOffice.setText("Remove");
        menuRemoveOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoveOfficeActionPerformed(evt);
            }
        });
        menuOffice.add(menuRemoveOffice);

        menuBar.add(menuOffice);

        menuDoctor.setText("Doctor");

        menuNewDoctor.setText("Add");
        menuNewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewDoctorActionPerformed(evt);
            }
        });
        menuDoctor.add(menuNewDoctor);

        menuEditDoctor.setText("Edit");
        menuEditDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditDoctorActionPerformed(evt);
            }
        });
        menuDoctor.add(menuEditDoctor);

        menuRemoveDoctor.setText("Remove");
        menuRemoveDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoveDoctorActionPerformed(evt);
            }
        });
        menuDoctor.add(menuRemoveDoctor);

        menuBar.add(menuDoctor);

        menuPatient.setText("Paciente");

        menuNewPatient.setText("Add");
        menuNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewPatientActionPerformed(evt);
            }
        });
        menuPatient.add(menuNewPatient);

        menuEditPatient.setText("Edit");
        menuEditPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditPatientActionPerformed(evt);
            }
        });
        menuPatient.add(menuEditPatient);

        menuRemovePatient.setText("Remove");
        menuRemovePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemovePatientActionPerformed(evt);
            }
        });
        menuPatient.add(menuRemovePatient);

        menuBar.add(menuPatient);

        menuReport.setText("Buscar");

        searchDoctor.setText("Doctor");
        searchDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDoctorActionPerformed(evt);
            }
        });
        menuReport.add(searchDoctor);

        jMenuItem3.setText("Paciente");
        menuReport.add(jMenuItem3);

        menuBar.add(menuReport);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRemoveOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoveOfficeActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "deleteOffice");
    }//GEN-LAST:event_menuRemoveOfficeActionPerformed

    private void menuNewHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewHospitalActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "newHospital");
    }//GEN-LAST:event_menuNewHospitalActionPerformed

    private void menuNewOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewOfficeActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "newOffice");
    }//GEN-LAST:event_menuNewOfficeActionPerformed

    private void menuEditOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditOfficeActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "editOffice");
    }//GEN-LAST:event_menuEditOfficeActionPerformed

    private void menuNewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewDoctorActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "newDoctor");
    }//GEN-LAST:event_menuNewDoctorActionPerformed

    private void menuEditDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditDoctorActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "showDoctor");
    }//GEN-LAST:event_menuEditDoctorActionPerformed

    private void menuRemoveDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoveDoctorActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "removeDoctor");
    }//GEN-LAST:event_menuRemoveDoctorActionPerformed

    private void menuNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewPatientActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "newPatient");
    }//GEN-LAST:event_menuNewPatientActionPerformed

    private void menuEditPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditPatientActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "editPatient");
    }//GEN-LAST:event_menuEditPatientActionPerformed

    private void menuRemovePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemovePatientActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "removePatient");
    }//GEN-LAST:event_menuRemovePatientActionPerformed

    private void searchDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDoctorActionPerformed
        
    }//GEN-LAST:event_searchDoctorActionPerformed

    private void menuAboutHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutHospitalActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "aboutHospital");
    }//GEN-LAST:event_menuAboutHospitalActionPerformed

    private void menuSelectHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSelectHospitalActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "selectHospital");
    }//GEN-LAST:event_menuSelectHospitalActionPerformed

    private void inicioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioMenuActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "inicioPanel");
    }//GEN-LAST:event_inicioMenuActionPerformed

    private void inicioMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMenuMouseClicked
        // TODO add your handling code here:
           CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "inicioPanel");
    }//GEN-LAST:event_inicioMenuMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutHospital;
    private Interfaz.Paneles.CreateNewDoctorsOffice createNewDoctorsOffice1;
    private Interfaz.Paneles.CreateNewHospital createNewHospital1;
    private Interfaz.Paneles.DeleteDoctorsOffice deleteDoctorsOffice1;
    private javax.swing.JPanel deleteOffice;
    private javax.swing.JPanel editDoctor;
    private Interfaz.Paneles.EditDoctorsOffice editDoctorsOffice1;
    private javax.swing.JPanel editOffice;
    private javax.swing.JPanel editPatient;
    private javax.swing.JMenu inicioMenu;
    private javax.swing.JPanel inicioPanel;
    private Interfaz.Paneles.InicioPanel inicioPanel1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem menuAboutHospital;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuDoctor;
    private javax.swing.JMenuItem menuEditDoctor;
    private javax.swing.JMenuItem menuEditOffice;
    private javax.swing.JMenuItem menuEditPatient;
    private javax.swing.JMenu menuHospital;
    private javax.swing.JMenuItem menuNewDoctor;
    private javax.swing.JMenuItem menuNewHospital;
    private javax.swing.JMenuItem menuNewOffice;
    private javax.swing.JMenuItem menuNewPatient;
    private javax.swing.JMenu menuOffice;
    private javax.swing.JMenu menuPatient;
    private javax.swing.JMenuItem menuRemoveDoctor;
    private javax.swing.JMenuItem menuRemoveOffice;
    private javax.swing.JMenuItem menuRemovePatient;
    private javax.swing.JMenu menuReport;
    private javax.swing.JMenuItem menuSelectHospital;
    private javax.swing.JPanel newDoctor;
    private javax.swing.JPanel newHospital;
    private javax.swing.JPanel newOffice;
    private javax.swing.JPanel newPatient;
    private javax.swing.JPanel removeDoctor;
    private javax.swing.JPanel removePatient;
    private javax.swing.JMenuItem searchDoctor;
    private javax.swing.JPanel selectHospital;
    private javax.swing.JPanel showDoctor;
    private Interfaz.Paneles.ShowDoctor showDoctor1;
    // End of variables declaration//GEN-END:variables

	private void initSaveButtonsListeners() {
		this.createNewHospital1.getSaveButton().addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewHospitalAction(evt);
            }
        });
	}
	
	public void saveNewHospitalAction(java.awt.event.ActionEvent evt){
		Hospital h = this.createNewHospital1.getHospital();
		this.hospitals.add(h);
		this.createNewHospital1.clearFields();
		//System.out.println(this.hospitals.get(0).getAddress());
	}
}
