/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Paneles;

import java.awt.CardLayout;

/**
 *
 * @author oscar
 */
public class MainWindow extends javax.swing.JFrame {

	/**
	 * Creates new form MainWindow
	 */
	public MainWindow() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        newHospital = new javax.swing.JPanel();
        newPatient = new javax.swing.JPanel();
        newOffice = new javax.swing.JPanel();
        newDoctor = new javax.swing.JPanel();
        editPatient = new javax.swing.JPanel();
        editOffice = new javax.swing.JPanel();
        editDoctor = new javax.swing.JPanel();
        removePatient = new javax.swing.JPanel();
        removeOffice = new javax.swing.JPanel();
        removeDoctor = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuHospital = new javax.swing.JMenu();
        menuNewHospital = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuOffice = new javax.swing.JMenu();
        menuNewOffice = new javax.swing.JMenuItem();
        menuEditOffice = new javax.swing.JMenuItem();
        menuRemoveOffice = new javax.swing.JMenuItem();
        menuDoctor = new javax.swing.JMenu();
        menuNewDoctor = new javax.swing.JMenuItem();
        menuEditDoctor = new javax.swing.JMenuItem();
        menuRemoveDoctor = new javax.swing.JMenuItem();
        menuPatient = new javax.swing.JMenu();
        menuNewPatient = new javax.swing.JMenuItem();
        menuEditPatient = new javax.swing.JMenuItem();
        menuRemovePatient = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout newHospitalLayout = new javax.swing.GroupLayout(newHospital);
        newHospital.setLayout(newHospitalLayout);
        newHospitalLayout.setHorizontalGroup(
            newHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        newHospitalLayout.setVerticalGroup(
            newHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        mainPanel.add(newHospital, "newHospital");

        javax.swing.GroupLayout newPatientLayout = new javax.swing.GroupLayout(newPatient);
        newPatient.setLayout(newPatientLayout);
        newPatientLayout.setHorizontalGroup(
            newPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        newPatientLayout.setVerticalGroup(
            newPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        mainPanel.add(newPatient, "newPatient");

        javax.swing.GroupLayout newOfficeLayout = new javax.swing.GroupLayout(newOffice);
        newOffice.setLayout(newOfficeLayout);
        newOfficeLayout.setHorizontalGroup(
            newOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        newOfficeLayout.setVerticalGroup(
            newOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        mainPanel.add(newOffice, "newOffice");

        javax.swing.GroupLayout newDoctorLayout = new javax.swing.GroupLayout(newDoctor);
        newDoctor.setLayout(newDoctorLayout);
        newDoctorLayout.setHorizontalGroup(
            newDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        newDoctorLayout.setVerticalGroup(
            newDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        mainPanel.add(newDoctor, "newDoctor");

        javax.swing.GroupLayout editPatientLayout = new javax.swing.GroupLayout(editPatient);
        editPatient.setLayout(editPatientLayout);
        editPatientLayout.setHorizontalGroup(
            editPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        editPatientLayout.setVerticalGroup(
            editPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        mainPanel.add(editPatient, "editPatient");

        javax.swing.GroupLayout editOfficeLayout = new javax.swing.GroupLayout(editOffice);
        editOffice.setLayout(editOfficeLayout);
        editOfficeLayout.setHorizontalGroup(
            editOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        editOfficeLayout.setVerticalGroup(
            editOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        mainPanel.add(editOffice, "editOffice");

        javax.swing.GroupLayout editDoctorLayout = new javax.swing.GroupLayout(editDoctor);
        editDoctor.setLayout(editDoctorLayout);
        editDoctorLayout.setHorizontalGroup(
            editDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        editDoctorLayout.setVerticalGroup(
            editDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        mainPanel.add(editDoctor, "editDoctor");

        javax.swing.GroupLayout removePatientLayout = new javax.swing.GroupLayout(removePatient);
        removePatient.setLayout(removePatientLayout);
        removePatientLayout.setHorizontalGroup(
            removePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        removePatientLayout.setVerticalGroup(
            removePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        mainPanel.add(removePatient, "removePatient");

        javax.swing.GroupLayout removeOfficeLayout = new javax.swing.GroupLayout(removeOffice);
        removeOffice.setLayout(removeOfficeLayout);
        removeOfficeLayout.setHorizontalGroup(
            removeOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        removeOfficeLayout.setVerticalGroup(
            removeOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        mainPanel.add(removeOffice, "removeOffice");

        javax.swing.GroupLayout removeDoctorLayout = new javax.swing.GroupLayout(removeDoctor);
        removeDoctor.setLayout(removeDoctorLayout);
        removeDoctorLayout.setHorizontalGroup(
            removeDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
        );
        removeDoctorLayout.setVerticalGroup(
            removeDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        mainPanel.add(removeDoctor, "removeDoctor");

        menuHospital.setText("Hospital");

        menuNewHospital.setText("New");
        menuNewHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewHospitalActionPerformed(evt);
            }
        });
        menuHospital.add(menuNewHospital);

        jMenuItem1.setText("Select");
        menuHospital.add(jMenuItem1);

        menuBar.add(menuHospital);

        menuOffice.setText("Office");

        menuNewOffice.setText("Add");
        menuNewOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewOfficeActionPerformed(evt);
            }
        });
        menuOffice.add(menuNewOffice);

        menuEditOffice.setText("Edit");
        menuEditOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditOfficeActionPerformed(evt);
            }
        });
        menuOffice.add(menuEditOffice);

        menuRemoveOffice.setText("Remove");
        menuRemoveOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoveOfficeActionPerformed(evt);
            }
        });
        menuOffice.add(menuRemoveOffice);

        menuBar.add(menuOffice);

        menuDoctor.setText("Doctor");

        menuNewDoctor.setText("Add");
        menuNewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewDoctorActionPerformed(evt);
            }
        });
        menuDoctor.add(menuNewDoctor);

        menuEditDoctor.setText("Edit");
        menuEditDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditDoctorActionPerformed(evt);
            }
        });
        menuDoctor.add(menuEditDoctor);

        menuRemoveDoctor.setText("Remove");
        menuRemoveDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoveDoctorActionPerformed(evt);
            }
        });
        menuDoctor.add(menuRemoveDoctor);

        menuBar.add(menuDoctor);

        menuPatient.setText("Patient");

        menuNewPatient.setText("Add");
        menuNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewPatientActionPerformed(evt);
            }
        });
        menuPatient.add(menuNewPatient);

        menuEditPatient.setText("Edit");
        menuEditPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditPatientActionPerformed(evt);
            }
        });
        menuPatient.add(menuEditPatient);

        menuRemovePatient.setText("Remove");
        menuRemovePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemovePatientActionPerformed(evt);
            }
        });
        menuPatient.add(menuRemovePatient);

        menuBar.add(menuPatient);

        menuReport.setText("Report");

        jMenuItem2.setText("Doctor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuReport.add(jMenuItem2);

        jMenuItem3.setText("Person");
        menuReport.add(jMenuItem3);

        menuBar.add(menuReport);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRemoveOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoveOfficeActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "removeOffice");
    }//GEN-LAST:event_menuRemoveOfficeActionPerformed

    private void menuNewHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewHospitalActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "newHospital");
    }//GEN-LAST:event_menuNewHospitalActionPerformed

    private void menuNewOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewOfficeActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "newOffice");
    }//GEN-LAST:event_menuNewOfficeActionPerformed

    private void menuEditOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditOfficeActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "editOffice");
    }//GEN-LAST:event_menuEditOfficeActionPerformed

    private void menuNewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewDoctorActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "newDoctor");
    }//GEN-LAST:event_menuNewDoctorActionPerformed

    private void menuEditDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditDoctorActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "editDoctor");
    }//GEN-LAST:event_menuEditDoctorActionPerformed

    private void menuRemoveDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoveDoctorActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "removeDoctor");
    }//GEN-LAST:event_menuRemoveDoctorActionPerformed

    private void menuNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewPatientActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "newPatient");
    }//GEN-LAST:event_menuNewPatientActionPerformed

    private void menuEditPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditPatientActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "editPatient");
    }//GEN-LAST:event_menuEditPatientActionPerformed

    private void menuRemovePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemovePatientActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
		card.show(mainPanel, "removePatient");
    }//GEN-LAST:event_menuRemovePatientActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel editDoctor;
    private javax.swing.JPanel editOffice;
    private javax.swing.JPanel editPatient;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuDoctor;
    private javax.swing.JMenuItem menuEditDoctor;
    private javax.swing.JMenuItem menuEditOffice;
    private javax.swing.JMenuItem menuEditPatient;
    private javax.swing.JMenu menuHospital;
    private javax.swing.JMenuItem menuNewDoctor;
    private javax.swing.JMenuItem menuNewHospital;
    private javax.swing.JMenuItem menuNewOffice;
    private javax.swing.JMenuItem menuNewPatient;
    private javax.swing.JMenu menuOffice;
    private javax.swing.JMenu menuPatient;
    private javax.swing.JMenuItem menuRemoveDoctor;
    private javax.swing.JMenuItem menuRemoveOffice;
    private javax.swing.JMenuItem menuRemovePatient;
    private javax.swing.JMenu menuReport;
    private javax.swing.JPanel newDoctor;
    private javax.swing.JPanel newHospital;
    private javax.swing.JPanel newOffice;
    private javax.swing.JPanel newPatient;
    private javax.swing.JPanel removeDoctor;
    private javax.swing.JPanel removeOffice;
    private javax.swing.JPanel removePatient;
    // End of variables declaration//GEN-END:variables
}
